# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  rental-toy-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: rental-toy-mysql
    volumes:
      - rental-toy-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rental-toy
      - MYSQL_DATABASE=rental-toy
      - MYSQL_USER=rental-toy
      - MYSQL_PASSWORD=rental-toy

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: rental-toy-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql